-- Check what shipping/contact columns exist in PS_DOC_HDR
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' 
  AND TABLE_NAME = 'PS_DOC_HDR' 
  AND (COLUMN_NAME LIKE 'SHIP%' 
       OR COLUMN_NAME LIKE '%PHONE%' 
       OR COLUMN_NAME LIKE '%EMAIL%' 
       OR COLUMN_NAME LIKE '%NAME%'
       OR COLUMN_NAME LIKE '%ADRS%'
       OR COLUMN_NAME LIKE '%CITY%'
       OR COLUMN_NAME LIKE '%STATE%'
       OR COLUMN_NAME LIKE '%ZIP%'
       OR COLUMN_NAME LIKE '%CNTRY%')
ORDER BY COLUMN_NAME;
