use WOODYS_CP;
/*
SELECT Items.ITEM_NO AS 'ITEM NUMBER', Items.DESCR AS 'DESCRIPTION', ITEMS.STK_UNIT 'UOM', Items.QTY_ON_HND 'ON HAND',
	(SELECT TOP(1) T2.BUS_DAT FROM PS_TKT_HIST_LIN T2 WHERE T2.ITEM_NO = items.ITEM_NO ORDER BY T2.BUS_DAT DESC) AS 'TRANSACTION DATE', 
	(SELECT T3.NAM FROM PO_VEND T3 WHERE T3.VEND_NO = Items.ITEM_VEND_NO) AS 'PRIMARY VENDOR' 
FROM VI_IM_ITEM_WITH_INV_AND_INV_TOTS Items ORDER BY ITEM_NO
*/

SELECT
	IM_ITEM.ITEM_NO AS 'ITEM NUMBER',
	IM_ITEM.DESCR AS 'DESCRIPTION',
	MAX(T2.BUS_DAT) AS 'TRANSACTION Date',
	T3.NAM AS 'PRIMARY VENDOR'
FROM IM_ITEM
	LEFT JOIN PS_TKT_HIST_LIN T2 ON T2.ITEM_NO = IM_ITEM.ITEM_NO and BUS_DAT >= '20250301'
	LEFT JOIN PO_VEND T3 ON T3.VEND_NO = IM_ITEM.ITEM_VEND_NO
GROUP BY IM_ITEM.ITEM_NO, IM_ITEM.DESCR, T3.NAM 
ORDER BY IM_ITEM.ITEM_NO