USE WOODYS_CP;
GO

-- ============================================
-- DIAGNOSTIC: Find which field is causing truncation
-- ============================================

-- Check the test record data lengths
SELECT 
    'Test Record Field Lengths' AS CheckType,
    STAGING_ID,
    BATCH_ID,
    LEN(ISNULL(NAM, '')) AS NAM_LEN,
    LEN(ISNULL(FST_NAM, '')) AS FST_NAM_LEN,
    LEN(ISNULL(LST_NAM, '')) AS LST_NAM_LEN,
    LEN(ISNULL(EMAIL_ADRS_1, '')) AS EMAIL_LEN,
    LEN(ISNULL(ADRS_1, '')) AS ADRS_1_LEN,
    LEN(ISNULL(CITY, '')) AS CITY_LEN,
    LEN(ISNULL(STATE, '')) AS STATE_LEN,
    LEN(ISNULL(ZIP_COD, '')) AS ZIP_LEN,
    LEN(ISNULL(PROF_COD_1, '')) AS PROF_COD_1_LEN,
    LEN(ISNULL(TAX_COD, '')) AS TAX_COD_LEN,
    LEN(ISNULL(CATEG_COD, '')) AS CATEG_COD_LEN,
    LEN(ISNULL(SLS_REP, '')) AS SLS_REP_LEN,
    LEN(ISNULL(SHIP_VIA_COD, '')) AS SHIP_VIA_COD_LEN,
    LEN(ISNULL(SHIP_ZONE_COD, '')) AS SHIP_ZONE_COD_LEN,
    LEN(ISNULL(STMNT_COD, '')) AS STMNT_COD_LEN,
    LEN(ISNULL(COMMNT, '')) AS COMMNT_LEN,
    LEN(ISNULL(CUST_NAM_TYP, '')) AS CUST_NAM_TYP_LEN,
    LEN(ISNULL(EMAIL_STATEMENT, '')) AS EMAIL_STATEMENT_LEN,
    LEN(ISNULL(RPT_EMAIL, '')) AS RPT_EMAIL_LEN,
    LEN(ISNULL(INCLUDE_IN_MARKETING_MAILOUTS, '')) AS MARKETING_LEN
FROM dbo.USER_CUSTOMER_STAGING
WHERE BATCH_ID = 'TEST_BATCH_001';

-- Check AR_CUST column lengths (actual database schema)
SELECT 
    'AR_CUST Column Lengths' AS CheckType,
    COLUMN_NAME,
    CHARACTER_MAXIMUM_LENGTH AS MAX_LENGTH,
    DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND TABLE_NAME = 'AR_CUST'
  AND DATA_TYPE IN ('varchar', 'nvarchar', 'char', 'nchar')
ORDER BY COLUMN_NAME;

-- Check what the procedure would insert (simulate the SELECT)
SELECT 
    'Simulated Insert Values' AS CheckType,
    LEFT(CAST(10036 AS VARCHAR(15)), 15) AS CUST_NO_LEN,
    LEN(LEFT('Test Customer Company', 40)) AS NAM_LEN,
    LEN(LEFT(UPPER('Test Customer Company'), 40)) AS NAM_UPR_LEN,
    LEN('C') AS CUST_TYP_LEN,
    LEN('N') AS PROMPT_NAM_ADRS_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 10)) AS SLS_REP_LEN,
    LEN(LEFT('01', 10)) AS STR_ID_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 10)) AS SHIP_VIA_COD_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 10)) AS SHIP_ZONE_COD_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 10)) AS STMNT_COD_LEN,
    LEN(LEFT(ISNULL(NULL, 'B'), 1)) AS CUST_NAM_TYP_LEN,
    LEN(LEFT(ISNULL(NULL, 'N'), 1)) AS EMAIL_STATEMENT_LEN,
    LEN(LEFT(ISNULL(NULL, 'N'), 1)) AS RPT_EMAIL_LEN,
    LEN(LEFT(ISNULL(NULL, 'N'), 1)) AS INCLUDE_IN_MARKETING_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 15)) AS FST_NAM_LEN,
    LEN(LEFT(UPPER(ISNULL(NULL, '')), 15)) AS FST_NAM_UPR_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 25)) AS LST_NAM_LEN,
    LEN(LEFT(UPPER(ISNULL(NULL, '')), 25)) AS LST_NAM_UPR_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 10)) AS SALUTATION_LEN,
    LEN(LEFT('123 Main Street', 40)) AS ADRS_1_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 40)) AS ADRS_2_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 40)) AS ADRS_3_LEN,
    LEN(LEFT('Miami', 20)) AS CITY_LEN,
    LEN(LEFT('FL', 10)) AS STATE_LEN,
    LEN(LEFT('33101', 15)) AS ZIP_COD_LEN,
    LEN(LEFT(ISNULL(NULL, 'US'), 20)) AS CNTRY_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 25)) AS PHONE_1_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 25)) AS PHONE_2_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 25)) AS MBL_PHONE_1_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 25)) AS MBL_PHONE_2_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 25)) AS FAX_1_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 25)) AS FAX_2_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 40)) AS CONTCT_1_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 40)) AS CONTCT_2_LEN,
    LEN(LEFT('test@example.com', 50)) AS EMAIL_ADRS_1_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 50)) AS EMAIL_ADRS_2_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 100)) AS URL_1_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 100)) AS URL_2_LEN,
    LEN(LEFT(ISNULL(NULL, 'RETAIL'), 10)) AS CATEG_COD_LEN,
    LEN(LEFT('TIER1', 10)) AS PROF_COD_1_LEN,
    LEN(LEFT(ISNULL(NULL, 'FL-BROWAR'), 10)) AS TAX_COD_LEN,
    LEN(LEFT(ISNULL(NULL, ''), 50)) AS COMMNT_LEN,
    LEN('INTEG') AS LST_MAINT_USR_ID_LEN;

GO

