-- Quick Migration: Add PROF_COD_1 column to USER_CUSTOMER_STAGING
-- This column is required for tier pricing (TIER1, TIER2, etc.)
-- Run this in SSMS on WOODYS_CP database

USE WOODYS_CP;
GO

-- Add PROF_COD_1 column if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'dbo' 
               AND TABLE_NAME = 'USER_CUSTOMER_STAGING' 
               AND COLUMN_NAME = 'PROF_COD_1')
BEGIN
    ALTER TABLE dbo.USER_CUSTOMER_STAGING ADD PROF_COD_1 VARCHAR(10);
    PRINT 'Added PROF_COD_1 column to USER_CUSTOMER_STAGING';
END
ELSE
BEGIN
    PRINT 'PROF_COD_1 column already exists in USER_CUSTOMER_STAGING';
END
GO

-- Verify
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' 
  AND TABLE_NAME = 'USER_CUSTOMER_STAGING'
  AND COLUMN_NAME = 'PROF_COD_1';
GO



